### ISSUE TITLE
add imports as section on features

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-docs#154]
![Screen Shot 2023-06-08 at 9 15 15 PM](https://github.com/terrastruct/d2-docs/assets/3120367/fe4598f1-1eeb-48e0-b0af-740bd18822cb)

**Comment by katwangy** [comment]
![export](https://github.com/terrastruct/d2-docs/assets/102620103/845773a0-2783-48a9-90e2-78f597a385e3)
![import](https://github.com/terrastruct/d2-docs/assets/102620103/7e2d65b7-11a2-47a9-8465-3c272ea50c56)
