### ISSUE TITLE
explain more about `direction`

### ISSUE THREAD

**Issue by alixander** [terrastruct/d2-docs#21]

**Comment by alixander** [comment]
@edvardchen it exists in the doc: https://d2lang.com/tour/layouts/#direction

very light rn, but hopefully makes it clear how to set!

**Comment by edvardchen** [comment]
directly in the code? like
```d2
direction: right
a -> b
```
or passing to the command `d2 --direction right ...`?

**Comment by alixander** [comment]
yeah directly in the code like that. sorry for the confusion, i'll do this tomorrow

**Comment by edvardchen** [comment]
It requires version `0.1.0`, quite fresh. But the latest version of d2 on brew is still `0.0.13`. Not sure why

**Comment by alixander** [comment]
@edvardchen shoot, sorry about that, nice catch. also didn't know but someone submitted d2 to homebrew core, so our install script needs to account for this
