### ISSUE TITLE
edit this page error: Not Found

### ISSUE THREAD

**Issue by marcusatiliusregulus** [terrastruct/d2-docs#23]
Clicking on any "Edit this page" button on <https://d2lang.com> just shows a "Not Found" message.

Tested with the ["edit this page"](<https://github.com/terrastruct/d2-docs/docs/tour/intro.md>) button on <https://d2lang.com/tour/intro/>

**Comment by marcusatiliusregulus** [comment]
It seems you have to append `/edit/master` to your `editUrl` in [docusaurus.config.js](https://github.com/terrastruct/d2-docs/blob/ed02cec558ba930d9cfd3c2e5926e43c5ee9b513/docusaurus.config.js#L20) so the final url looks like: <https://github.com/terrastruct/d2-docs/edit/master/docs/tour/intro.md>

**Comment by alixander** [comment]
i'll just remove it for now, people don't have write access to master anyway. ty @marcusatiliusregulus
