### ISSUE TITLE
Add rendered example of all shapes

### ISSUE THREAD

**Issue by DeflateAwning** [terrastruct/d2-docs#89]
On [the shapes page](https://d2lang.com/tour/shapes/#example), it would be great if you showed rendered examples for every shape, with the name of that shape as the text inside the shape.

**Comment by alixander** [comment]
@DeflateAwning good point! I'll just copy this test case over: https://github.com/terrastruct/d2/blob/master/e2etests/testdata/stable/all_shapes/elk/sketch.exp.svg
